services:
  techweb-backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@techweb-db:5432/TechWeb-24-25
      - JWT_SECRET=supersecret
    depends_on:
      - techweb-db
    restart: unless-stopped

  techweb-frontend:
    build:
      context: ./techweb-frontend
    volumes:
      - ./techweb-frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - techweb-backend
    restart: unless-stopped

  techweb-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: TechWeb-24-25
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
