export const strayCatComments = [
  "Qualcuno sa se ha un nome?",
  "I bambini del quartiere gli hanno dato dell'acqua.",
  "Mi ha seguito fino a casa, era molto affettuoso.",
  "Ha fatto amicizia con il mio cane!",
  "Ha rubato un pezzo di pollo dal mio piatto!",
  "Ha fatto amicizia con il postino.",
  "Mi segue quando porto fuori la spazzatura.",
  "L'ho visto litigare con un altro gatto.",
  "Sembra che aspetti qualcuno ogni mattina.",
  "Ha un musetto davvero simpatico."
];

export const strayCatDescriptions = [
  "Sembra che abbia fame... qualcuno l'ha visto di recente?",
  "Poverino, era sotto la pioggia vicino alla stazione.",
  "L'ho visto dormire su una sedia fuori dal bar.",
  "Era nascosto sotto una macchina, sembrava spaventato.",
  "L'ho visto giocare con altri gatti nel parco.",
  "Ha una zampa ferita, forse serve aiuto.",
  "L'ho nutrito ieri sera, sembrava molto affamato.",
  "Si è rifugiato nel mio cortile durante il temporale.",
  "Ha il pelo arruffato, forse non sta bene.",
  "Si avvicina solo se non ci sono cani nei dintorni.",
  "L'ho visto spesso vicino alla scuola elementare.",
  "Ha un collare rosso, forse si è perso.",
  "Miagola spesso davanti al supermercato.",
  "Si arrampica sugli alberi del viale principale.",
  "L'ho trovato che dormiva nella scatola delle consegne.",
  "Qualcuno vuole adottarlo? Sembra molto dolce.",
  "Ha paura delle persone, ma si avvicina per il cibo.",
  "L'ho visto inseguire una farfalla nel giardino.",
  "Si nasconde sotto le panchine del parco.",
  "Ha gli occhi molto grandi e curiosi.",
  "L'ho visto solo di notte, è molto timido.",
  "Ha trovato riparo nel garage del vicino.",
  "Mi sembra che sia in cerca di una casa.",
  "Ieri era in compagnia di altri due gatti.",
  "Ha un miagolio molto particolare.",
  "L'ho visto giocare con una pallina di carta.",
  "Si lascia accarezzare solo da chi conosce.",
  "Sembra che abbia partorito da poco.",
  "L'ho visto arrampicarsi sul tetto del condominio.",
  "Ha paura dei rumori forti.",
  "Si avvicina quando sente il rumore delle crocchette.",
  "L'ho trovato che dormiva sulla mia auto.",
  "Ha il pelo bianco con delle macchie nere.",
  "Sembra molto giovane, forse è un cucciolo.",
  "L'ho visto spesso vicino alla fermata dell'autobus.",
  "Si rifugia sotto il portico quando piove.",
  "L'ho visto giocare con una foglia secca.",
  "Ha un orecchio piegato, forse si è ferito."
];
