import { CityCoordinate, CityRegion } from "./types";

export const safeUrbanCoordinates: CityCoordinate[] = [
  // Europa
  { name: "Roma", lat: 41.9028, lng: 12.4964, country: "IT" },
  { name: "Milano", lat: 45.4642, lng: 9.1900, country: "IT" },
  { name: "Napoli", lat: 40.8518, lng: 14.2681, country: "IT" },
  { name: "Venezia", lat: 45.4408, lng: 12.3155, country: "IT" },
  { name: "Firenze", lat: 43.7696, lng: 11.2558, country: "IT" },
  { name: "Bologna", lat: 44.4949, lng: 11.3426, country: "IT" },
  { name: "Torino", lat: 45.0703, lng: 7.6869, country: "IT" },
  { name: "Palermo", lat: 38.1157, lng: 13.3613, country: "IT" },
  { name: "Genova", lat: 44.4056, lng: 8.9463, country: "IT" },
  { name: "Catania", lat: 37.5079, lng: 15.0830, country: "IT" },
  { name: "Bari", lat: 41.1171, lng: 16.8719, country: "IT" },
  { name: "Madrid", lat: 40.4168, lng: -3.7038, country: "ES" },
  { name: "Barcelona", lat: 41.3851, lng: 2.1734, country: "ES" },
  { name: "Paris", lat: 48.8566, lng: 2.3522, country: "FR" },
  { name: "London", lat: 51.5074, lng: -0.1278, country: "UK" },
  { name: "Berlin", lat: 52.5200, lng: 13.4050, country: "DE" },
  { name: "Amsterdam", lat: 52.3676, lng: 4.9041, country: "NL" },
  { name: "Athens", lat: 37.9838, lng: 23.7275, country: "GR" },
  { name: "Istanbul", lat: 41.0082, lng: 28.9784, country: "TR" },
  { name: "Moscow", lat: 55.7558, lng: 37.6173, country: "RU" },

  // Nord America
  { name: "New York", lat: 40.7128, lng: -74.0060, country: "US" },
  { name: "San Francisco", lat: 37.7749, lng: -122.4194, country: "US" },
  { name: "Chicago", lat: 41.8781, lng: -87.6298, country: "US" },
  { name: "Los Angeles", lat: 34.0522, lng: -118.2437, country: "US" },
  { name: "Toronto", lat: 43.6532, lng: -79.3832, country: "CA" },
  { name: "Montreal", lat: 45.5017, lng: -73.5673, country: "CA" },
  { name: "Mexico City", lat: 19.4326, lng: -99.1332, country: "MX" },

  // Sud America
  { name: "Buenos Aires", lat: -34.6037, lng: -58.3816, country: "AR" },
  { name: "Santiago", lat: -33.4489, lng: -70.6693, country: "CL" },
  { name: "Lima", lat: -12.0464, lng: -77.0428, country: "PE" },
  { name: "Rio de Janeiro", lat: -22.9068, lng: -43.1729, country: "BR" },
  { name: "São Paulo", lat: -23.5505, lng: -46.6333, country: "BR" },

  // Asia
  { name: "Tokyo", lat: 35.6895, lng: 139.6917, country: "JP" },
  { name: "Osaka", lat: 34.6937, lng: 135.5023, country: "JP" },
  { name: "Seoul", lat: 37.5665, lng: 126.9780, country: "KR" },
  { name: "Beijing", lat: 39.9042, lng: 116.4074, country: "CN" },
  { name: "Shanghai", lat: 31.2304, lng: 121.4737, country: "CN" },
  { name: "Bangkok", lat: 13.7563, lng: 100.5018, country: "TH" },
  { name: "Mumbai", lat: 19.0760, lng: 72.8777, country: "IN" },
  { name: "New Delhi", lat: 28.6139, lng: 77.2090, country: "IN" },
  { name: "Dubai", lat: 25.2048, lng: 55.2708, country: "AE" },

  // Africa
  { name: "Cairo", lat: 30.0444, lng: 31.2357, country: "EG" },
  { name: "Casablanca", lat: 33.5731, lng: -7.5898, country: "MA" },
  { name: "Nairobi", lat: -1.2921, lng: 36.8219, country: "KE" },
  { name: "Lagos", lat: 6.5244, lng: 3.3792, country: "NG" },
  { name: "Johannesburg", lat: -26.2041, lng: 28.0473, country: "ZA" },
  { name: "Cape Town", lat: -33.9249, lng: 18.4241, country: "ZA" },

  // Oceania
  { name: "Sydney", lat: -33.8688, lng: 151.2093, country: "AU" },
  { name: "Melbourne", lat: -37.8136, lng: 144.9631, country: "AU" },
  { name: "Auckland", lat: -36.8485, lng: 174.7633, country: "NZ" },
  { name: "Wellington", lat: -41.2866, lng: 174.7756, country: "NZ" },
];

// Titoli specifici per avvistamenti di gatti randagi
export const strayCatTitles = [
  "Gatto rosso cerca famiglia",
  "Micino nero nel parco",
  "Gattino grigio timido",
  "Soriano affettuoso",
  "Gatto bianco e nero",
  "Piccolo randagio affamato",
  "Micio tigrato dolce",
  "Gatto dalle orecchie tagliate",
  "Siamese mix in difficoltà",
  "Gattina possibile mamma",
  "Gatto anziano solitario",
  "Cucciolo di gatto smarrito",
  "Micio dal collare rotto",
  "Gatto a pelo lungo",
  "Randagio con gli occhi verdi",
  "Gattino tutto nero",
  "Soriano con la coda corta",
  "Gatto calico femminile",
  "Micio arancione vivace",
  "Gatto tartarugato",
  "Piccolo gatto bianco",
  "Micio con una zampa ferita",
  "Gatto europeo comune",
  "Randagio dal pelo folto",
  "Gattino con gli occhi azzurri",
  "Micio trovatello",
  "Gatto di strada esperto",
  "Piccola gatta incinta",
  "Soriano con il muso bianco",
  "Gatto nero con pettorina bianca",
  "Micio dal carattere dolce",
  "Randagio socievole",
  "Gattino appena svezzato",
  "Micio abituato alle persone",
  "Gatto dal pelo arruffato",
  "Piccolo felino coraggioso",
  "Micio in cerca di coccole",
  "Gatto di quartiere",
  "Randagio dalla coda lunga",
  "Gattino dai baffi bianchi"
];

export const strayCatComments = [
  "Qualcuno sa se ha un nome? Lo vedo spesso vicino al tabaccaio.",
  "I bambini del quartiere gli hanno costruito una piccola cuccia.",
  "Mi ha seguito fino a casa, come se mi conoscesse da sempre.",
  "Ha fatto amicizia con il mio cane, si annusano ogni mattina!",
  "Ha rubato un pezzo di pollo dal mio piatto, ma era troppo carino per arrabbiarsi.",
  "Il postino gli lascia sempre qualche crocchetta.",
  "Mi segue quando porto fuori la spazzatura... è diventata un'abitudine!",
  "L'ho visto litigare con un altro gatto per un posto al sole.",
  "Ogni mattina aspetta fuori dal bar, come se aspettasse qualcuno.",
  "Ha un musetto simpatico, ma non si lascia avvicinare.",
  "Stamattina era seduto davanti alla farmacia, sembrava aspettare qualcuno.",
  "Ieri sera si è nascosto sotto la mia auto per la pioggia.",
  "Ha uno sguardo furbo, sembra conoscere tutti i trucchi del quartiere.",
  "Quando passo con la bici mi segue per un po', poi si ferma e si sdraia.",
  "Ha imparato a riconoscere il rumore delle chiavi: arriva sempre quando torno a casa.",
  "L'ho visto giocare con una foglia secca, sembrava divertirsi un sacco.",
  "Ogni tanto sparisce per giorni, poi torna come se nulla fosse.",
  "Ha una zampa bianca e una nera, lo riconosco subito.",
  "Si mette sempre vicino al termosifone del bar d'inverno.",
  "Quando c'è il mercato, si aggira tra i banchi in cerca di cibo.",
];

export const strayCatDescriptions = [
  "Sembra affamato, si aggira tra i bidoni vicino alla piazzetta.",
  "Poverino, ieri sera era fradicio sotto la pioggia alla stazione.",
  "Dormiva su una sedia fuori dal bar come se fosse casa sua.",
  "Era nascosto sotto una macchina, tremava per la paura.",
  "Giocava con altri gatti nel parco come se fosse il capo del gruppo.",
  "Ha una zampa ferita, si muove zoppicando... qualcuno può aiutarlo?",
  "Ieri sera ha mangiato il cibo che ho lasciato, sembrava affamato da giorni.",
  "Durante il temporale è corso nel mio cortile a cercare riparo.",
  "Ha il pelo arruffato e gli occhi un po’ spenti, forse non sta bene.",
  "Si avvicina solo quando non ci sono cani o troppe persone.",
  "Sta spesso vicino alla scuola, forse aspetta qualche bambino.",
  "Ha un collare rosso sbiadito... potrebbe essersi perso.",
  "Miagola davanti al supermercato, come se sapesse che lì trova cibo.",
  "Si arrampica sempre sul solito albero del viale.",
  "Stamattina dormiva nella scatola delle consegne come un piccolo re.",
  "Sembra molto dolce, qualcuno dovrebbe adottarlo.",
  "Ha paura delle persone, ma si avvicina se lasci del cibo.",
  "Ieri inseguiva una farfalla nel giardino, sembrava un cucciolo.",
  "Si nasconde sotto le panchine del parco, soprattutto nel pomeriggio.",
  "Ha degli occhi enormi, sembrano guardarti dentro.",
  "Si muove solo di notte, è timido ma curioso.",
  "Ha trovato rifugio nel garage del vicino, ci torna ogni sera.",
  "Sembra in cerca di una casa, guarda ogni porta con speranza.",
  "Era con altri due gatti, sembravano una piccola famiglia.",
  "Il suo miagolio è così strano che ormai lo riconosco da lontano.",
  "Giocava con una pallina di carta che qualcuno gli ha lasciato.",
  "Si lascia accarezzare solo da chi conosce bene.",
  "Forse ha partorito da poco, era molto protettiva.",
  "È salito sul tetto e da lì osservava tutta la strada.",
  "Scappa al minimo rumore, ma resta a pochi metri.",
  "Corre quando sente il rumore del sacchetto di crocchette.",
  "Stamattina dormiva sul cofano della mia auto, scaldandosi al sole.",
  "Ha il pelo bianco e nero, come un panda in miniatura.",
  "Sembra un cucciolo, ha uno sguardo ingenuo e curioso.",
  "Lo vedo spesso vicino alla fermata dell'autobus, come se aspettasse qualcuno.",
  "Quando piove si infila sotto il portico della farmacia.",
  "Giocava con una foglia secca, come se fosse un giocattolo.",
  "Ha un orecchio piegato, forse da una vecchia ferita.",
];

// Regioni delle città per la validazione delle coordinate
export const cityRegions: CityRegion[] = safeUrbanCoordinates.map(city => ({
  name: city.name,
  latMin: city.lat - 0.2, // Area di 0.4 gradi di latitudine (circa 44 km)
  latMax: city.lat + 0.2,
  lonMin: city.lng - 0.2, // Area di 0.4 gradi di longitudine
  lonMax: city.lng + 0.2,
  country: city.country
}));
